### ISSUE TITLE
The compiler is waiting for input via stdin error

### ISSUE THREAD

**Issue by kirill-onufrienko-db** [roman01la/webpack-closure-compiler#13]
Hi. I'm experience following error during the build process. It happens occasinally and often vanishes during second run. Could you help?

[17:32:35][ERROR] Caught error:  Error: main.619a56322ad38930ab35.bundle.js from Closure Compiler
[17:32:35][ERROR] The compiler is waiting for input via stdin.
[17:32:35][ERROR] 
[17:32:35][ERROR]     at C:\work\teamcity_buildagents_ssd\ba1\work\c6436fccfd414f1[censored]\node_modules\webpack-closure-compiler\index.js:58:20
[17:32:35][ERROR]     at ChildProcess.<anonymous> (C:\work\teamcity_buildagents_ssd\ba1\work\c6436fccfd414f1[censored]\node_modules\webpack-closure-compiler\lib\runner.js:70:12)
[17:32:35][ERROR]     at emitTwo (events.js:106:13)
[17:32:35][ERROR]     at ChildProcess.emit (events.js:191:7)
[17:32:35][ERROR]     at maybeClose (internal/child_process.js:850:16)
[17:32:35][ERROR]     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by roman01la** [comment]
@kirillonufreinko Hello! I'm sorry, I'm not using this plugin at the moment and I don't have time to look into your problem. Any help and PR are welcome!

**Comment by shouvik** [comment]
I was looking into this issue and I think it's related to `Class properties` not being a part of ES6 specs. Has anyone else run into this issue?

**Comment by roman01la** [comment]
@shouvik Would be nice if you could provide a minimal repro.

**Comment by roman01la** [comment]
closing due to no activity
