### ISSUE TITLE
EPIPE error with React project

### ISSUE THREAD

**Issue by shashwattt-Pretlist** [roman01la/webpack-closure-compiler#30]
Trying to implement for optimisation, getting error as, any help or suggestion appreciated. 

> events.js:160
      throw er; // Unhandled 'error' event
      ^
    Error: write EPIPE
    at exports._errnoException (util.js:1012:11)
    at WriteWrap.afterWrite (net.js:793:14)

My config.js is as follows

```
var webpack = require('webpack');
var ClosureCompilerPlugin = require('webpack-closure-compiler');

module.exports = {
    entry: {
        main: './src/index.js',
        vendor: ['moment', 'pubsub-js', 'socket.io-client', 'axios', 'react', 'react-router'],
    },
    output: {
        path: './build/',
        filename: 'static/js/bundle.js',
        //chunkFilename: 'static/js/[id].bundle.js',
    },
    devServer: {
        compress:true,
        inline: true,
        port: 3333
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                query: {
                    // stage: 0,
                    presets: ["react", "es2015", "stage-0"],
                    plugins: ['./relay_build/babelRelayPlugin'].map(require.resolve)
                }
            },
            {
                loader: 'json-loader',
                test: /\.json$/
            },
            {
                test: /\.scss$/,
                loaders: ['style-loader', 'css-loader', 'sass-loader']
            },
            {
                test: /\.(gif|jpe?g|png|ico)$/,
                loader: 'url-loader?limit=10000'
            },
            {
                test: /\.(otf|eot|svg|ttf|woff|woff2).*$/,
                loader: 'url-loader?limit=10000'
            }
        ]
    },
    plugins: [
    new ClosureCompilerPlugin({
          compiler: {
            language_in: 'ECMASCRIPT6',
            language_out: 'ECMASCRIPT5',
            compilation_level: 'ADVANCED'
          },
          concurrency: 3,
        })
  ],
}
```

**Comment by roman01la** [comment]
@shashwattt-Pretlist A minimal repro would help to understand what's going on there. Thanks.

**Comment by mhdatie** [comment]
Experiencing same issue. Not using the plugin makes it work.

**Comment by jarofghosts** [comment]
I have the same issue, but it doesn't occur if I use the `jsCompiler: true` option.

**Comment by HoraceShmorace** [comment]
I had this problem on my Mac. You simply need to install the Java SDK. http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

The compiler uses Java. `jsCompiler: true` will use the pure JS compiler, which is why @jarofghosts could get around this issue.

It should be called out as a system requirement in the README.

**Comment by roman01la** [comment]
@HoraceShmorace Thanks!

@shashwattt-Pretlist  please let us know if this solves your issue

**Comment by roman01la** [comment]
@HoraceShmorace FYI, I've added *Requirements* section which refers to Java SDK dependency https://github.com/roman01la/webpack-closure-compiler#requirements

**Comment by roman01la** [comment]
closing due to no activity
